### ISSUE TITLE
problem with running

### ISSUE THREAD

**Issue by fengluying** [AkiraHero/diffindscene#4]
When I follow the instructions, I meet the following issues:

(diffindscene) luying@luying-LEGION-REN7000K-26IRB:~/Desktop/3D_Generate/DiffInScene/diffindscene-main$ python main/test.py --cfg_dir utils/config/samples/cascaded_ldm_ucond
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/luying/Desktop/3D_Generate/DiffInScene/diffindscene-main/main/test.py", line 14, in <module>
    git_version = subprocess.check_output(["git", 'rev-parse', 'HEAD']).strip().decode()
  File "/home/luying/anaconda3/envs/diffindscene/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/luying/anaconda3/envs/diffindscene/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

Could you please offer some instructions to solve this problem?

**Comment by AkiraHero** [comment]
You can just comment line 14-15.
